enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.1.cjs

packageExtensions:
  react-dom@*:
    peerDependencies:
      react: "*"

compressionLevel: mixed

enableTelemetry: false
